export interface BlogTopic {
  key: string;
  brief: string; // direction given to the writer - the model still picks its own title
  category: "car-tips" | "travel-guides" | "company-news" | "rwanda-tourism" | "car-maintenance";
  primaryKeyword: string;
  linkTargets: { path: string; label: string }[];
}

// A rotating bank of specific, non-generic angles - all targeting "Kigali car
// rental" / "car rental Rwanda" variants without repeating the same page
// three times a week. Each entry's linkTargets point at real, already-live
// routes (see src/app/sitemap.ts) so every generated post gets genuine,
// relevant internal links, not fabricated ones.
export const BLOG_TOPICS: BlogTopic[] = [
  { key: "airport-arrival-guide", brief: "What to expect picking up a rental car at Kigali International Airport, step by step", category: "travel-guides", primaryKeyword: "Kigali airport car rental", linkTargets: [{ path: "/kigali-airport-car-rental", label: "Kigali airport car rental" }, { path: "/airport-driver-service", label: "airport driver service" }] },
  { key: "self-drive-vs-chauffeur", brief: "Self-drive vs a chauffeur-driven car in Rwanda - which suits which traveler", category: "car-tips", primaryKeyword: "self drive car rental Kigali", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental in Rwanda" }, { path: "/chauffeur-service-rwanda", label: "chauffeur service in Rwanda" }] },
  { key: "gorilla-trekking-logistics", brief: "Planning vehicle logistics for a gorilla trekking trip to Volcanoes National Park", category: "travel-guides", primaryKeyword: "car rental for gorilla trekking Rwanda", linkTargets: [{ path: "/volcanoes-4x4-rental", label: "Volcanoes National Park 4x4 rental" }, { path: "/4x4-car-rental-rwanda", label: "4x4 car rental in Rwanda" }] },
  { key: "akagera-vehicle-guide", brief: "Choosing the right vehicle for an Akagera National Park game drive", category: "travel-guides", primaryKeyword: "Akagera safari car rental", linkTargets: [{ path: "/akagera-safari-rental", label: "Akagera safari rental" }, { path: "/akagera-game-drive", label: "Akagera game drive vehicles" }] },
  { key: "nyungwe-trip-planning", brief: "Planning a Nyungwe Forest canopy walk trip and what vehicle you need to get there", category: "travel-guides", primaryKeyword: "Nyungwe Forest car rental", linkTargets: [{ path: "/nyungwe-forest-safari", label: "Nyungwe Forest safari rental" }, { path: "/4x4-car-rental-rwanda", label: "4x4 car rental Rwanda" }] },
  { key: "budget-rental-tips", brief: "Practical ways to get an affordable car rental deal in Kigali without hidden costs", category: "car-tips", primaryKeyword: "cheap car rental Kigali", linkTargets: [{ path: "/cheap-car-rental-kigali", label: "cheap car rental in Kigali" }, { path: "/fleet", label: "our full fleet" }] },
  { key: "luxury-business-travel", brief: "Choosing a luxury or executive car rental for business travel in Kigali", category: "car-tips", primaryKeyword: "luxury car rental Kigali", linkTargets: [{ path: "/luxury-car-rental-kigali", label: "luxury car rental in Kigali" }, { path: "/business-driver-service", label: "business driver service" }] },
  { key: "wedding-event-transport", brief: "Organizing wedding convoy and event transport hire in Kigali", category: "car-tips", primaryKeyword: "event transport Kigali", linkTargets: [{ path: "/event-transport-driver", label: "event transport driver service" }, { path: "/chauffeur-service-rwanda", label: "chauffeur service" }] },
  { key: "kigali-traffic-tips", brief: "Practical tips for driving through Kigali's traffic and hilly streets as a visitor", category: "car-tips", primaryKeyword: "driving in Kigali", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive rental in Rwanda" }, { path: "/driver-car-hire-kigali", label: "driver car hire in Kigali" }] },
  { key: "rental-requirements", brief: "Documents, licence and deposit requirements to rent a car in Rwanda as a foreigner", category: "car-tips", primaryKeyword: "car rental requirements Rwanda", linkTargets: [{ path: "/how-it-works", label: "how our booking process works" }, { path: "/fleet", label: "available cars" }] },
  { key: "land-cruiser-vs-prado", brief: "Land Cruiser vs Prado - which 4x4 to rent for Rwanda's roads and terrain", category: "car-tips", primaryKeyword: "Land Cruiser rental Rwanda", linkTargets: [{ path: "/land-cruiser-rental-rwanda", label: "Land Cruiser rental in Rwanda" }, { path: "/prado-rental-kigali", label: "Prado rental in Kigali" }] },
  { key: "camping-road-trip", brief: "Planning a camping road trip in Rwanda with a rooftop tent vehicle", category: "travel-guides", primaryKeyword: "rooftop tent car rental Rwanda", linkTargets: [{ path: "/camping-car-rental-rwanda", label: "camping car rental in Rwanda" }, { path: "/rooftop-tent-car-rental-rwanda", label: "rooftop tent car rental" }] },
  { key: "lake-kivu-road-trip", brief: "A road trip guide from Kigali to Lake Kivu (Rubavu/Karongi) by rental car", category: "rwanda-tourism", primaryKeyword: "Kigali to Lake Kivu car rental", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental" }, { path: "/fleet", label: "our fleet" }] },
  { key: "musanze-volcanoes-drive", brief: "Driving distance, road conditions and time from Kigali to Musanze / Volcanoes National Park", category: "rwanda-tourism", primaryKeyword: "Kigali to Musanze car rental", linkTargets: [{ path: "/volcanoes-4x4-rental", label: "Volcanoes National Park rental" }, { path: "/4x4-car-rental-rwanda", label: "4x4 car rental" }] },
  { key: "huye-butare-road-trip", brief: "A historical road trip from Kigali to Huye (Butare) by rental car", category: "rwanda-tourism", primaryKeyword: "Kigali to Huye car rental", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental in Rwanda" }, { path: "/fleet", label: "our fleet" }] },
  { key: "cross-border-driving", brief: "What to know about cross-border driving rules between Rwanda and Uganda with a rental car", category: "car-tips", primaryKeyword: "cross border car rental Rwanda", linkTargets: [{ path: "/4x4-car-rental-rwanda", label: "4x4 car rental Rwanda" }, { path: "/long-term-car-rental-rwanda", label: "long-term car rental" }] },
  { key: "rainy-season-driving", brief: "Why a 4x4 matters in Rwanda's rainy season and how to drive safely on wet hills", category: "car-tips", primaryKeyword: "4x4 car rental Rwanda rainy season", linkTargets: [{ path: "/4x4-car-rental-rwanda", label: "4x4 car rental in Rwanda" }, { path: "/self-drive-rwanda", label: "self-drive rental" }] },
  { key: "private-driver-vs-taxi", brief: "Private driver hire vs taxi apps in Kigali - cost, comfort and reliability compared", category: "car-tips", primaryKeyword: "private driver Kigali", linkTargets: [{ path: "/private-driver-kigali", label: "private driver in Kigali" }, { path: "/driver-car-hire-kigali", label: "driver car hire in Kigali" }] },
  { key: "corporate-driver-service", brief: "Booking a business driver for meetings, conferences and corporate travel in Kigali", category: "car-tips", primaryKeyword: "business driver service Kigali", linkTargets: [{ path: "/business-driver-service", label: "business driver service" }, { path: "/chauffeur-service-rwanda", label: "chauffeur service Rwanda" }] },
  { key: "city-tour-driver", brief: "A guided city tour of Kigali's top sights with a private driver", category: "rwanda-tourism", primaryKeyword: "Kigali city tour driver", linkTargets: [{ path: "/city-tour-driver", label: "Kigali city tour driver" }, { path: "/private-driver-kigali", label: "private driver Kigali" }] },
  { key: "daily-rate-breakdown", brief: "A transparent breakdown of what's included in a daily car rental rate in Kigali", category: "car-tips", primaryKeyword: "car rental rates Kigali", linkTargets: [{ path: "/cheap-car-rental-kigali", label: "affordable car rental in Kigali" }, { path: "/fleet", label: "our fleet and pricing" }] },
  { key: "book-direct-benefits", brief: "Why booking directly with a local Kigali car rental company beats third-party booking sites", category: "company-news", primaryKeyword: "book car rental Kigali direct", linkTargets: [{ path: "/fleet", label: "our fleet" }, { path: "/book-now", label: "book now" }] },
  { key: "one-way-extended-rental", brief: "How one-way and extended/long-term rental options work in Rwanda", category: "car-tips", primaryKeyword: "long term car rental Rwanda", linkTargets: [{ path: "/long-term-car-rental-rwanda", label: "long-term car rental in Rwanda" }, { path: "/long-term/monthly", label: "monthly rental plans" }] },
  { key: "family-road-trip", brief: "Packing and vehicle tips for a family road trip across Rwanda", category: "rwanda-tourism", primaryKeyword: "family car rental Rwanda", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental" }, { path: "/camping-car-rental-rwanda", label: "camping car rental" }] },
  { key: "solo-female-travel-safety", brief: "Practical safety advice for solo female travelers renting a car in Rwanda", category: "travel-guides", primaryKeyword: "solo travel car rental Rwanda", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental" }, { path: "/driver-car-hire-kigali", label: "driver car hire in Kigali" }] },
  { key: "fuel-cost-planning", brief: "Estimating fuel costs and mileage for a self-drive road trip in Rwanda", category: "car-tips", primaryKeyword: "self drive Rwanda fuel cost", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive rental in Rwanda" }, { path: "/fleet", label: "our fleet" }] },
  { key: "best-time-to-visit", brief: "The best time of year to visit Rwanda and rent a car for safari season", category: "rwanda-tourism", primaryKeyword: "best time to rent a car in Rwanda", linkTargets: [{ path: "/akagera-safari-rental", label: "Akagera safari rental" }, { path: "/volcanoes-4x4-rental", label: "Volcanoes National Park rental" }] },
  { key: "insurance-and-terms", brief: "What's typically included in a rental agreement - insurance, mileage and deposits explained", category: "car-tips", primaryKeyword: "car rental insurance Rwanda", linkTargets: [{ path: "/how-it-works", label: "how it works" }, { path: "/fleet", label: "our fleet" }] },
  { key: "suv-vs-sedan", brief: "SUV vs sedan - which handles Rwanda's hills and unpaved roads better", category: "car-tips", primaryKeyword: "SUV rental Rwanda", linkTargets: [{ path: "/4x4-car-rental-rwanda", label: "4x4 car rental Rwanda" }, { path: "/fleet", label: "our fleet" }] },
  { key: "ngo-diplomatic-leasing", brief: "Long-term vehicle leasing options for NGOs, diplomats and expat staff in Kigali", category: "company-news", primaryKeyword: "long term car lease Kigali", linkTargets: [{ path: "/long-term-car-rental-rwanda", label: "long-term car rental" }, { path: "/long-term/monthly", label: "monthly rental plans" }] },
  { key: "top-day-trips", brief: "The best day-trip destinations from Kigali reachable by rental car", category: "rwanda-tourism", primaryKeyword: "day trips from Kigali by car", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental" }, { path: "/fleet", label: "our fleet" }] },
  { key: "chauffeur-etiquette", brief: "Chauffeur etiquette and tipping culture for visitors hiring a driver in Rwanda", category: "travel-guides", primaryKeyword: "chauffeur service Rwanda etiquette", linkTargets: [{ path: "/chauffeur-service-rwanda", label: "chauffeur service in Rwanda" }, { path: "/private-driver-kigali", label: "private driver Kigali" }] },
  { key: "last-minute-deals", brief: "How to find and use last-minute car rental deals in Kigali", category: "car-tips", primaryKeyword: "last minute car rental Kigali", linkTargets: [{ path: "/deals/last-minute", label: "last-minute deals" }, { path: "/cheap-car-rental-kigali", label: "cheap car rental in Kigali" }] },
  { key: "vip-wedding-convoy", brief: "Planning a VIP wedding convoy with luxury vehicles in Kigali", category: "car-tips", primaryKeyword: "wedding car hire Kigali", linkTargets: [{ path: "/event-transport-driver", label: "event transport service" }, { path: "/luxury-car-rental-kigali", label: "luxury car rental" }] },
  { key: "kigali-to-akagera-drive", brief: "Driving distance, time and road conditions from Kigali to Akagera National Park", category: "rwanda-tourism", primaryKeyword: "Kigali to Akagera driving distance", linkTargets: [{ path: "/akagera-safari-rental", label: "Akagera safari rental" }, { path: "/akagera-game-drive", label: "Akagera game drive" }] },
  { key: "kigali-to-nyungwe-drive", brief: "Driving distance, time and road conditions from Kigali to Nyungwe Forest", category: "rwanda-tourism", primaryKeyword: "Kigali to Nyungwe driving distance", linkTargets: [{ path: "/nyungwe-forest-safari", label: "Nyungwe Forest safari rental" }, { path: "/4x4-car-rental-rwanda", label: "4x4 car rental" }] },
  { key: "kigali-to-volcanoes-drive", brief: "Driving distance, time and road conditions from Kigali to Volcanoes National Park", category: "rwanda-tourism", primaryKeyword: "Kigali to Volcanoes National Park driving distance", linkTargets: [{ path: "/volcanoes-4x4-rental", label: "Volcanoes National Park rental" }, { path: "/4x4-car-rental-rwanda", label: "4x4 car rental" }] },
  { key: "conference-business-trip", brief: "Renting a car or driver for a conference or business trip in Kigali", category: "company-news", primaryKeyword: "business trip car rental Kigali", linkTargets: [{ path: "/business-driver-service", label: "business driver service" }, { path: "/luxury-car-rental-kigali", label: "luxury car rental" }] },
  { key: "moto-vs-car-safety", brief: "Motorbike taxis vs renting a car in Kigali - safety and comfort compared", category: "car-tips", primaryKeyword: "car rental vs moto Kigali", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental" }, { path: "/driver-car-hire-kigali", label: "driver car hire in Kigali" }] },
  { key: "self-drive-safety-tips", brief: "Road safety and maintenance checks self-drive tourists should do before a long drive", category: "car-maintenance", primaryKeyword: "self drive road safety Rwanda", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive car rental" }, { path: "/how-it-works", label: "how it works" }] },
  { key: "breakdown-what-to-do", brief: "What to do if your rental car breaks down on a Rwandan road", category: "car-maintenance", primaryKeyword: "rental car breakdown Rwanda", linkTargets: [{ path: "/how-it-works", label: "how our support works" }, { path: "/fleet", label: "our fleet" }] },
  { key: "tires-hilly-terrain", brief: "Tire care and road-condition tips for Rwanda's hilly, sometimes unpaved terrain", category: "car-maintenance", primaryKeyword: "4x4 rental Rwanda road conditions", linkTargets: [{ path: "/4x4-car-rental-rwanda", label: "4x4 car rental Rwanda" }, { path: "/self-drive-rwanda", label: "self-drive rental" }] },
  { key: "prep-for-safari-drive", brief: "Preparing a rental vehicle for a long safari game-drive day in Akagera", category: "car-maintenance", primaryKeyword: "Akagera game drive vehicle prep", linkTargets: [{ path: "/akagera-safari-rental", label: "Akagera safari rental" }, { path: "/4x4-car-rental-rwanda", label: "4x4 car rental" }] },
  { key: "seasonal-car-care", brief: "Seasonal car care in Rwanda - dust in dry season, mud in rainy season", category: "car-maintenance", primaryKeyword: "car rental Rwanda seasonal care", linkTargets: [{ path: "/self-drive-rwanda", label: "self-drive rental" }, { path: "/4x4-car-rental-rwanda", label: "4x4 car rental" }] },
  { key: "group-minibus-transport", brief: "Booking minibus or group transport in Kigali for churches, schools and large groups", category: "car-tips", primaryKeyword: "group transport hire Kigali", linkTargets: [{ path: "/event-transport-driver", label: "event transport service" }, { path: "/long-term/monthly", label: "monthly rental plans" }] },
  { key: "photography-filming-trips", brief: "Vehicle needs for photography and filming road trips across Rwanda", category: "travel-guides", primaryKeyword: "4x4 rental for filming Rwanda", linkTargets: [{ path: "/4x4-car-rental-rwanda", label: "4x4 car rental" }, { path: "/camping-car-rental-rwanda", label: "camping car rental" }] },
  { key: "senior-traveler-comfort", brief: "Comfortable, low-stress car rental options in Kigali for retirees and senior travelers", category: "travel-guides", primaryKeyword: "comfortable car rental Kigali seniors", linkTargets: [{ path: "/luxury-car-rental-kigali", label: "luxury car rental" }, { path: "/chauffeur-service-rwanda", label: "chauffeur service" }] },
  { key: "diaspora-visiting-home", brief: "How diaspora Rwandans visiting home use car rental for family trips and errands", category: "company-news", primaryKeyword: "car rental for diaspora Rwanda", linkTargets: [{ path: "/fleet", label: "our fleet" }, { path: "/book-now", label: "book now" }] },
  { key: "airport-hotel-transfer-cost", brief: "Comparing hotel shuttle costs to private airport transfer car rental in Kigali", category: "car-tips", primaryKeyword: "Kigali airport transfer cost", linkTargets: [{ path: "/kigali-airport-car-rental", label: "Kigali airport car rental" }, { path: "/airport-driver-service", label: "airport driver service" }] },
  { key: "rwanda-guided-tours-transport", brief: "Arranging guided transport for multi-day Rwanda tours with a driver", category: "rwanda-tourism", primaryKeyword: "guided transport Rwanda", linkTargets: [{ path: "/rwanda-guided-transport", label: "guided transport in Rwanda" }, { path: "/private-driver-kigali", label: "private driver Kigali" }] },
  { key: "compare-rental-companies", brief: "What to check when comparing car rental companies in Kigali before booking", category: "car-tips", primaryKeyword: "compare car rental companies Kigali", linkTargets: [{ path: "/fleet", label: "our fleet" }, { path: "/how-it-works", label: "how it works" }] },
];
